name: Notify JIRA about contribution

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  notify-jira:
    if: ${{contains(fromJson('["denieler", "TomasSlama", "OleksandrNechai", "OndrejTuma", "dmaklygin1", "LashaJini"]'), github.event.pull_request.user.login)}}
    runs-on: ubuntu-latest
    env:
      JIRA_HOOK: ${{ secrets.JIRA_AUTOMATION_HOOK_FOR_NEW_CONTRIBUTION }}
    steps:
      - run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"data": {"author":"${{github.event.pull_request.user.login}}", "author_url":"${{github.event.pull_request.user.html_url}}", "title":"${{github.event.pull_request.title}}", "number":"${{github.event.pull_request.number}}", "url":"${{github.event.pull_request.html_url}}"}}' \
          ${{ env.JIRA_HOOK }}
