name: Request review on PRs

on:
  pull_request:
    types:
      - opened

jobs:
  request:
    name: Request reviews on opened PRs
    runs-on: ubuntu-latest

    steps:
      - name: Create PR review request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            octokit.rest.pulls.requestReviewers({
              owner: 'toptal',
              repo: 'picasso',
              pull_number: ${{ github.event.number }},
              team_reviewers: ['@toptal/fx-codeowners']
            })
